### ISSUE TITLE
Some icons in iconsets are not named

### ISSUE THREAD

**Issue by gkiely** [pluwen/awesome-iconjar#1]
Thanks for creating this awesome repo!

**Problem:** Some of the icons are not named so they don't show up in search including:
MFGlabs-iconset, Elegant icons

**Solution:** Add names to those icons

I'm happy to go through and rename them if you'd like, I'm guessing I can just update the names, save and then submit a PR?

Thanks.

**Comment by pluwen** [comment]
Sure.
