### ISSUE TITLE
[Q] What does 3-part pack mean

### ISSUE THREAD

**Issue by schroef** [pluwen/awesome-iconjar#3]
First of all awesome pack!

BUt what does 3-pack mean?

**Comment by pluwen** [comment]
Official: https://geticonjar.com/featured-icons/ Choose Free IconSet
3-Part: from Other WebSite.

**Comment by pluwen** [comment]
Deleted~

**Comment by schroef** [comment]
Ah okay, sort of clear now. Thanks!
